[project]
name = "mcpcrashcourse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-openai>=0.3.27",
    "mcp-use>=1.3.3",
    "mcp[cli]>=1.10.1",
]
